package CSharp.behavior;

/*Generated by MPS */


/**
 * Will be removed after 3.4
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This interface is not involved in the actual method invocation
 */
@Deprecated
public interface ICommon_member_declaration_block_4_1_BehaviorDescriptor {
}
