package CSharp.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.openapi.editor.cells.DefaultSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.OldNewCompositeSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.SChildSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;

public class Combined_join_clause_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_4fo8tt_a(editorContext, node);
  }
  private EditorCell createCollection_4fo8tt_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_4fo8tt_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_4fo8tt_a0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_4fo8tt_b0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_4fo8tt_c0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_4fo8tt_d0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_4fo8tt_e0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_4fo8tt_f0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_4fo8tt_g0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_4fo8tt_h0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_4fo8tt_i0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_4fo8tt_j0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_4fo8tt_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "join");
    editorCell.setCellId("Constant_4fo8tt_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_4fo8tt_b0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Combined_join_clause_Editor.Type_1SingleRoleHandler_4fo8tt_b0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f71b5L, 0x70aadf795f7486L, "Type_1"), editorContext);
    return provider.createCell();
  }
  private class Type_1SingleRoleHandler_4fo8tt_b0 extends SingleRoleCellProvider {
    public Type_1SingleRoleHandler_4fo8tt_b0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f71b5L, 0x70aadf795f7486L, "Type_1"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Type_1");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_4fo8tt_a1a(editorContext, node);
    }
    private EditorCell createConstant_4fo8tt_a1a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_4fo8tt_a1a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createRefNode_4fo8tt_c0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Combined_join_clause_Editor.Identifier_2SingleRoleHandler_4fo8tt_c0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f71b5L, 0x70aadf795f7487L, "Identifier_2"), editorContext);
    return provider.createCell();
  }
  private class Identifier_2SingleRoleHandler_4fo8tt_c0 extends SingleRoleCellProvider {
    public Identifier_2SingleRoleHandler_4fo8tt_c0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f71b5L, 0x70aadf795f7487L, "Identifier_2"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Identifier_2");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_4fo8tt_a2a(editorContext, node);
    }
    private EditorCell createConstant_4fo8tt_a2a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_4fo8tt_a2a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createConstant_4fo8tt_d0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "in");
    editorCell.setCellId("Constant_4fo8tt_d0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_4fo8tt_e0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Combined_join_clause_Editor.Expression_3SingleRoleHandler_4fo8tt_e0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f71b5L, 0x70aadf795f7488L, "Expression_3"), editorContext);
    return provider.createCell();
  }
  private class Expression_3SingleRoleHandler_4fo8tt_e0 extends SingleRoleCellProvider {
    public Expression_3SingleRoleHandler_4fo8tt_e0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f71b5L, 0x70aadf795f7488L, "Expression_3"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Expression_3");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_4fo8tt_a4a(editorContext, node);
    }
    private EditorCell createConstant_4fo8tt_a4a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_4fo8tt_a4a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createConstant_4fo8tt_f0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "on");
    editorCell.setCellId("Constant_4fo8tt_f0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_4fo8tt_g0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Combined_join_clause_Editor.Expression_4SingleRoleHandler_4fo8tt_g0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f71b5L, 0x70aadf795f7489L, "Expression_4"), editorContext);
    return provider.createCell();
  }
  private class Expression_4SingleRoleHandler_4fo8tt_g0 extends SingleRoleCellProvider {
    public Expression_4SingleRoleHandler_4fo8tt_g0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f71b5L, 0x70aadf795f7489L, "Expression_4"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Expression_4");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_4fo8tt_a6a(editorContext, node);
    }
    private EditorCell createConstant_4fo8tt_a6a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_4fo8tt_a6a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createConstant_4fo8tt_h0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "equals");
    editorCell.setCellId("Constant_4fo8tt_h0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_4fo8tt_i0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Combined_join_clause_Editor.Expression_5SingleRoleHandler_4fo8tt_i0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f71b5L, 0x70aadf795f748aL, "Expression_5"), editorContext);
    return provider.createCell();
  }
  private class Expression_5SingleRoleHandler_4fo8tt_i0 extends SingleRoleCellProvider {
    public Expression_5SingleRoleHandler_4fo8tt_i0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f71b5L, 0x70aadf795f748aL, "Expression_5"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Expression_5");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_4fo8tt_a8a(editorContext, node);
    }
    private EditorCell createConstant_4fo8tt_a8a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_4fo8tt_a8a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createRefNode_4fo8tt_j0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Combined_join_clause_Editor.Combined_join_clause_block_1_1_6SingleRoleHandler_4fo8tt_j0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f71b5L, 0x70aadf795f748bL, "Combined_join_clause_block_1_1_6"), editorContext);
    return provider.createCell();
  }
  private class Combined_join_clause_block_1_1_6SingleRoleHandler_4fo8tt_j0 extends SingleRoleCellProvider {
    public Combined_join_clause_block_1_1_6SingleRoleHandler_4fo8tt_j0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f71b5L, 0x70aadf795f748bL, "Combined_join_clause_block_1_1_6"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Combined_join_clause_block_1_1_6");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_4fo8tt_a9a(editorContext, node);
    }
    private EditorCell createConstant_4fo8tt_a9a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_4fo8tt_a9a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
}
