package CSharp.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.openapi.editor.cells.DefaultSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.OldNewCompositeSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.SChildSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;

public class Interface_member_declaration_block_1_2_1_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_aq2fd2_a(editorContext, node);
  }
  private EditorCell createCollection_aq2fd2_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_aq2fd2_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createRefNode_aq2fd2_a0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_aq2fd2_b0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_aq2fd2_c0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_aq2fd2_d0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_aq2fd2_e0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_aq2fd2_f0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_aq2fd2_g0(editorContext, node));
    return editorCell;
  }
  private EditorCell createRefNode_aq2fd2_a0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Interface_member_declaration_block_1_2_1_Editor.Identifier_1SingleRoleHandler_aq2fd2_a0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f7244L, 0x70aadf795f74e1L, "Identifier_1"), editorContext);
    return provider.createCell();
  }
  private class Identifier_1SingleRoleHandler_aq2fd2_a0 extends SingleRoleCellProvider {
    public Identifier_1SingleRoleHandler_aq2fd2_a0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f7244L, 0x70aadf795f74e1L, "Identifier_1"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Identifier_1");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_aq2fd2_a0a(editorContext, node);
    }
    private EditorCell createConstant_aq2fd2_a0a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_aq2fd2_a0a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createRefNode_aq2fd2_b0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Interface_member_declaration_block_1_2_1_Editor.Type_parameter_list_2SingleRoleHandler_aq2fd2_b0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f7244L, 0x70aadf795f74e2L, "Type_parameter_list_2"), editorContext);
    return provider.createCell();
  }
  private class Type_parameter_list_2SingleRoleHandler_aq2fd2_b0 extends SingleRoleCellProvider {
    public Type_parameter_list_2SingleRoleHandler_aq2fd2_b0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f7244L, 0x70aadf795f74e2L, "Type_parameter_list_2"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Type_parameter_list_2");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_aq2fd2_a1a(editorContext, node);
    }
    private EditorCell createConstant_aq2fd2_a1a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_aq2fd2_a1a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createConstant_aq2fd2_c0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "(");
    editorCell.setCellId("Constant_aq2fd2_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_aq2fd2_d0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Interface_member_declaration_block_1_2_1_Editor.Formal_parameter_list_3SingleRoleHandler_aq2fd2_d0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f7244L, 0x70aadf795f74e3L, "Formal_parameter_list_3"), editorContext);
    return provider.createCell();
  }
  private class Formal_parameter_list_3SingleRoleHandler_aq2fd2_d0 extends SingleRoleCellProvider {
    public Formal_parameter_list_3SingleRoleHandler_aq2fd2_d0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f7244L, 0x70aadf795f74e3L, "Formal_parameter_list_3"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Formal_parameter_list_3");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_aq2fd2_a3a(editorContext, node);
    }
    private EditorCell createConstant_aq2fd2_a3a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_aq2fd2_a3a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createConstant_aq2fd2_e0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, ")");
    editorCell.setCellId("Constant_aq2fd2_e0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_aq2fd2_f0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Interface_member_declaration_block_1_2_1_Editor.Type_parameter_constraints_clauses_4SingleRoleHandler_aq2fd2_f0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f7244L, 0x70aadf795f74e4L, "Type_parameter_constraints_clauses_4"), editorContext);
    return provider.createCell();
  }
  private class Type_parameter_constraints_clauses_4SingleRoleHandler_aq2fd2_f0 extends SingleRoleCellProvider {
    public Type_parameter_constraints_clauses_4SingleRoleHandler_aq2fd2_f0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f7244L, 0x70aadf795f74e4L, "Type_parameter_constraints_clauses_4"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Type_parameter_constraints_clauses_4");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_aq2fd2_a5a(editorContext, node);
    }
    private EditorCell createConstant_aq2fd2_a5a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_aq2fd2_a5a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createConstant_aq2fd2_g0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, ";");
    editorCell.setCellId("Constant_aq2fd2_g0");
    editorCell.setDefaultText("");
    return editorCell;
  }
}
