package CSharp.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.openapi.editor.cells.DefaultSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.OldNewCompositeSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.SChildSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;

public class Operator_declaration_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_11vpuu_a(editorContext, node);
  }
  private EditorCell createCollection_11vpuu_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_11vpuu_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_11vpuu_a0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_11vpuu_b0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_11vpuu_c0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_11vpuu_d0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_11vpuu_e0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_11vpuu_f0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_11vpuu_g0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_11vpuu_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "operator");
    editorCell.setCellId("Constant_11vpuu_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_11vpuu_b0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Operator_declaration_Editor.Overloadable_operator_1SingleRoleHandler_11vpuu_b0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f6fecL, 0x70aadf795f7306L, "Overloadable_operator_1"), editorContext);
    return provider.createCell();
  }
  private class Overloadable_operator_1SingleRoleHandler_11vpuu_b0 extends SingleRoleCellProvider {
    public Overloadable_operator_1SingleRoleHandler_11vpuu_b0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f6fecL, 0x70aadf795f7306L, "Overloadable_operator_1"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Overloadable_operator_1");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_11vpuu_a1a(editorContext, node);
    }
    private EditorCell createConstant_11vpuu_a1a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_11vpuu_a1a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createConstant_11vpuu_c0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "(");
    editorCell.setCellId("Constant_11vpuu_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_11vpuu_d0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Operator_declaration_Editor.Arg_declaration_2SingleRoleHandler_11vpuu_d0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f6fecL, 0x70aadf795f7307L, "Arg_declaration_2"), editorContext);
    return provider.createCell();
  }
  private class Arg_declaration_2SingleRoleHandler_11vpuu_d0 extends SingleRoleCellProvider {
    public Arg_declaration_2SingleRoleHandler_11vpuu_d0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f6fecL, 0x70aadf795f7307L, "Arg_declaration_2"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Arg_declaration_2");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_11vpuu_a3a(editorContext, node);
    }
    private EditorCell createConstant_11vpuu_a3a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_11vpuu_a3a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createRefNode_11vpuu_e0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Operator_declaration_Editor.Operator_declaration_block_1_1_3SingleRoleHandler_11vpuu_e0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f6fecL, 0x70aadf795f7308L, "Operator_declaration_block_1_1_3"), editorContext);
    return provider.createCell();
  }
  private class Operator_declaration_block_1_1_3SingleRoleHandler_11vpuu_e0 extends SingleRoleCellProvider {
    public Operator_declaration_block_1_1_3SingleRoleHandler_11vpuu_e0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f6fecL, 0x70aadf795f7308L, "Operator_declaration_block_1_1_3"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Operator_declaration_block_1_1_3");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_11vpuu_a4a(editorContext, node);
    }
    private EditorCell createConstant_11vpuu_a4a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_11vpuu_a4a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createConstant_11vpuu_f0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, ")");
    editorCell.setCellId("Constant_11vpuu_f0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_11vpuu_g0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Operator_declaration_Editor.Operator_declaration_block_1_2_4SingleRoleHandler_11vpuu_g0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f6fecL, 0x70aadf795f7309L, "Operator_declaration_block_1_2_4"), editorContext);
    return provider.createCell();
  }
  private class Operator_declaration_block_1_2_4SingleRoleHandler_11vpuu_g0 extends SingleRoleCellProvider {
    public Operator_declaration_block_1_2_4SingleRoleHandler_11vpuu_g0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f6fecL, 0x70aadf795f7309L, "Operator_declaration_block_1_2_4"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Operator_declaration_block_1_2_4");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_11vpuu_a6a(editorContext, node);
    }
    private EditorCell createConstant_11vpuu_a6a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_11vpuu_a6a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
}
