package CSharp.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.openapi.editor.cells.DefaultSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.OldNewCompositeSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.SChildSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;

public class Simple_embedded_statement_21_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_yvi2qy_a(editorContext, node);
  }
  private EditorCell createCollection_yvi2qy_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_yvi2qy_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_yvi2qy_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_yvi2qy_b0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_yvi2qy_c0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_yvi2qy_d0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_yvi2qy_e0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_yvi2qy_f0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_yvi2qy_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "fixed");
    editorCell.setCellId("Constant_yvi2qy_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_yvi2qy_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "(");
    editorCell.setCellId("Constant_yvi2qy_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_yvi2qy_c0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Simple_embedded_statement_21_Editor.Pointer_type_1SingleRoleHandler_yvi2qy_c0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f70adL, 0x70aadf795f73ceL, "Pointer_type_1"), editorContext);
    return provider.createCell();
  }
  private class Pointer_type_1SingleRoleHandler_yvi2qy_c0 extends SingleRoleCellProvider {
    public Pointer_type_1SingleRoleHandler_yvi2qy_c0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f70adL, 0x70aadf795f73ceL, "Pointer_type_1"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Pointer_type_1");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_yvi2qy_a2a(editorContext, node);
    }
    private EditorCell createConstant_yvi2qy_a2a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_yvi2qy_a2a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createRefNode_yvi2qy_d0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Simple_embedded_statement_21_Editor.Fixed_pointer_declarators_2SingleRoleHandler_yvi2qy_d0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f70adL, 0x70aadf795f73cfL, "Fixed_pointer_declarators_2"), editorContext);
    return provider.createCell();
  }
  private class Fixed_pointer_declarators_2SingleRoleHandler_yvi2qy_d0 extends SingleRoleCellProvider {
    public Fixed_pointer_declarators_2SingleRoleHandler_yvi2qy_d0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f70adL, 0x70aadf795f73cfL, "Fixed_pointer_declarators_2"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Fixed_pointer_declarators_2");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_yvi2qy_a3a(editorContext, node);
    }
    private EditorCell createConstant_yvi2qy_a3a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_yvi2qy_a3a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createConstant_yvi2qy_e0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, ")");
    editorCell.setCellId("Constant_yvi2qy_e0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_yvi2qy_f0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Simple_embedded_statement_21_Editor.Embedded_statement_3SingleRoleHandler_yvi2qy_f0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f70adL, 0x70aadf795f73d0L, "Embedded_statement_3"), editorContext);
    return provider.createCell();
  }
  private class Embedded_statement_3SingleRoleHandler_yvi2qy_f0 extends SingleRoleCellProvider {
    public Embedded_statement_3SingleRoleHandler_yvi2qy_f0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f70adL, 0x70aadf795f73d0L, "Embedded_statement_3"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Embedded_statement_3");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_yvi2qy_a5a(editorContext, node);
    }
    private EditorCell createConstant_yvi2qy_a5a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_yvi2qy_a5a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
}
