package CSharp.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.openapi.editor.cells.DefaultSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.OldNewCompositeSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.SChildSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;

public class Simple_embedded_statement_7_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_3vcvfq_a(editorContext, node);
  }
  private EditorCell createCollection_3vcvfq_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_3vcvfq_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_3vcvfq_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_3vcvfq_b0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_3vcvfq_c0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_3vcvfq_d0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_3vcvfq_e0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_3vcvfq_f0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_3vcvfq_g0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_3vcvfq_h0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_3vcvfq_i0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_3vcvfq_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "for");
    editorCell.setCellId("Constant_3vcvfq_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_3vcvfq_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "(");
    editorCell.setCellId("Constant_3vcvfq_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_3vcvfq_c0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Simple_embedded_statement_7_Editor.For_initializer_1SingleRoleHandler_3vcvfq_c0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f709fL, 0x70aadf795f73b9L, "For_initializer_1"), editorContext);
    return provider.createCell();
  }
  private class For_initializer_1SingleRoleHandler_3vcvfq_c0 extends SingleRoleCellProvider {
    public For_initializer_1SingleRoleHandler_3vcvfq_c0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f709fL, 0x70aadf795f73b9L, "For_initializer_1"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("For_initializer_1");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_3vcvfq_a2a(editorContext, node);
    }
    private EditorCell createConstant_3vcvfq_a2a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_3vcvfq_a2a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createConstant_3vcvfq_d0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, ";");
    editorCell.setCellId("Constant_3vcvfq_d0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_3vcvfq_e0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Simple_embedded_statement_7_Editor.Expression_2SingleRoleHandler_3vcvfq_e0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f709fL, 0x70aadf795f73baL, "Expression_2"), editorContext);
    return provider.createCell();
  }
  private class Expression_2SingleRoleHandler_3vcvfq_e0 extends SingleRoleCellProvider {
    public Expression_2SingleRoleHandler_3vcvfq_e0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f709fL, 0x70aadf795f73baL, "Expression_2"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Expression_2");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_3vcvfq_a4a(editorContext, node);
    }
    private EditorCell createConstant_3vcvfq_a4a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_3vcvfq_a4a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createConstant_3vcvfq_f0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, ";");
    editorCell.setCellId("Constant_3vcvfq_f0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_3vcvfq_g0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Simple_embedded_statement_7_Editor.For_iterator_3SingleRoleHandler_3vcvfq_g0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f709fL, 0x70aadf795f73bbL, "For_iterator_3"), editorContext);
    return provider.createCell();
  }
  private class For_iterator_3SingleRoleHandler_3vcvfq_g0 extends SingleRoleCellProvider {
    public For_iterator_3SingleRoleHandler_3vcvfq_g0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f709fL, 0x70aadf795f73bbL, "For_iterator_3"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("For_iterator_3");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_3vcvfq_a6a(editorContext, node);
    }
    private EditorCell createConstant_3vcvfq_a6a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_3vcvfq_a6a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createConstant_3vcvfq_h0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, ")");
    editorCell.setCellId("Constant_3vcvfq_h0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_3vcvfq_i0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Simple_embedded_statement_7_Editor.Embedded_statement_4SingleRoleHandler_3vcvfq_i0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f709fL, 0x70aadf795f73bcL, "Embedded_statement_4"), editorContext);
    return provider.createCell();
  }
  private class Embedded_statement_4SingleRoleHandler_3vcvfq_i0 extends SingleRoleCellProvider {
    public Embedded_statement_4SingleRoleHandler_3vcvfq_i0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f709fL, 0x70aadf795f73bcL, "Embedded_statement_4"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Embedded_statement_4");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_3vcvfq_a8a(editorContext, node);
    }
    private EditorCell createConstant_3vcvfq_a8a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_3vcvfq_a8a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
}
