package CSharp.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.openapi.editor.cells.DefaultSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.OldNewCompositeSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.SChildSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;

public class Simple_embedded_statement_18_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_8n0mwm_a(editorContext, node);
  }
  private EditorCell createCollection_8n0mwm_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_8n0mwm_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_8n0mwm_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_8n0mwm_b0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_8n0mwm_c0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_8n0mwm_d0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_8n0mwm_e0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_8n0mwm_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "using");
    editorCell.setCellId("Constant_8n0mwm_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_8n0mwm_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "(");
    editorCell.setCellId("Constant_8n0mwm_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_8n0mwm_c0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Simple_embedded_statement_18_Editor.Resource_acquisition_1SingleRoleHandler_8n0mwm_c0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f70aaL, 0x70aadf795f73caL, "Resource_acquisition_1"), editorContext);
    return provider.createCell();
  }
  private class Resource_acquisition_1SingleRoleHandler_8n0mwm_c0 extends SingleRoleCellProvider {
    public Resource_acquisition_1SingleRoleHandler_8n0mwm_c0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f70aaL, 0x70aadf795f73caL, "Resource_acquisition_1"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Resource_acquisition_1");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_8n0mwm_a2a(editorContext, node);
    }
    private EditorCell createConstant_8n0mwm_a2a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_8n0mwm_a2a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createConstant_8n0mwm_d0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, ")");
    editorCell.setCellId("Constant_8n0mwm_d0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_8n0mwm_e0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new Simple_embedded_statement_18_Editor.Embedded_statement_2SingleRoleHandler_8n0mwm_e0(node, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f70aaL, 0x70aadf795f73cbL, "Embedded_statement_2"), editorContext);
    return provider.createCell();
  }
  private class Embedded_statement_2SingleRoleHandler_8n0mwm_e0 extends SingleRoleCellProvider {
    public Embedded_statement_2SingleRoleHandler_8n0mwm_e0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0x5f522167449a4486L, 0x94654f30de6e5cecL, 0x70aadf795f70aaL, 0x70aadf795f73cbL, "Embedded_statement_2"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("Embedded_statement_2");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = createEmptyCell_internal(myEditorContext, myOwnerNode);

      installCellInfo(null, editorCell);
      return editorCell;
    }
    private EditorCell createEmptyCell_internal(EditorContext editorContext, SNode node) {
      return this.createConstant_8n0mwm_a4a(editorContext, node);
    }
    private EditorCell createConstant_8n0mwm_a4a(EditorContext editorContext, SNode node) {
      EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
      editorCell.setCellId("Constant_8n0mwm_a4a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
}
