package CSharp.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.PropertySupport;

public class REAL_LITERAL_PropertySupport extends PropertySupport {
  public boolean canSetValue(String value) {
    String testValue = null;
    if (value == null) {
      testValue = "";
    } else {
      testValue = value;
    }
    return testValue.matches("((([0-9])*\\.([0-9])+([eE](\\+|\\-)?([0-9])+)?([FfDdMm])?)|(([0-9])+([FfDdMm]|[eE](\\+|\\-)?([0-9])+([FfDdMm])?)))");
  }
}
